# Any snapshot for GHC >= 8.4 should work, we pick the most recent final LTS:
# (recent as of 2024-05-28)
resolver: lts-21.25

# See https://www.stackage.org/ "Latest releases per GHC version"
# for alternatives.
